### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by chen1474147** [mattloper/opendr#15]
Hi, I try to install it in Ubuntu, I download the source code and run make all.
Then I got such errors

python2.7 setup.py build_ext --inplace
Autogenerating opengl sources
Compiling contexts/ctx_mesa.pyx because it changed.
[1/1] Cythonizing contexts/ctx_mesa.pyx

Error compiling Cython file:
------------------------------------------------------------
...
"""
^
------------------------------------------------------------

contexts/ctx_mesa.pyx:1:0: 'opendr-master.contexts.ctx_mesa' is not a valid module name
Traceback (most recent call last):
  File "setup.py", line 153, in <module>
    main()
  File "setup.py", line 149, in main
    setup_opendr([mesa_ext()])
  File "setup.py", line 63, in setup_opendr
    ext_modules=cythonize(ext_modules)
  File "/usr/lib/python2.7/dist-packages/Cython/Build/Dependencies.py", line 877, in cythonize
    cythonize_one(*args)
  File "/usr/lib/python2.7/dist-packages/Cython/Build/Dependencies.py", line 997, in cythonize_one
    raise CompileError(None, pyx_file)
Cython.Compiler.Errors.CompileError: contexts/ctx_mesa.pyx
Makefile:3: recipe for target 'all' failed
make: *** [all] Error 1

Can you help me?

**Comment by imaginary-unit** [comment]
Same problem with Ubuntu 16.04. Any help?

**Comment by aeoleader** [comment]
you can use pip to install opendr, if the problem persists

**Comment by runa91** [comment]
Same problem with 16.04 when using this git version as above. And with pip I get:

# pip install opendr
Collecting opendr
  Using cached opendr-0.76.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-r609yikz/opendr/setup.py", line 40
        print "Downloading %s" % osmesa_fname
                             ^
    SyntaxError: Missing parentheses in call to 'print'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-r609yikz/opendr/

**Comment by imaginary-unit** [comment]
@runa91, you're likely running it with pip from python 3.*. This package only supports python 2.*

**Comment by jzubizarreta** [comment]
Same problem. Did you solve it? 
I am using pip to install with Python 2.7 but I get the following error:

Cython.Compiler.Errors.CompileError: contexts/ctx_mesa.pyx
Command "python setup.py egg_info" failed with error code 1

**Comment by SpiritBear000** [comment]
I have successfully installed by using 'pip install opendr‘ with python2!!!!

**Comment by neonb88** [comment]
@SpiritBear000 Can you please paste system information?

**Comment by shamimsareem** [comment]
@SpiritBear000 Please let us know the information how to solve this problem.

**Comment by SpiritBear000** [comment]
> @SpiritBear000 Please let us know the information how to solve this problem.

Just using command ‘pip install opendr’ . But only work in python2 env

**Comment by SpiritBear000** [comment]
Just using command ‘pip install opendr’ . But only work in python2 env

**Comment by delaprada** [comment]
I have successfully installed opendr with python2, but not with `pip install opendr`.

take the following steps:
1. git clone opendr repo:
```
git clone https://github.com/mattloper/opendr
```
2. wget download OSMesa to `opendr/contexts` directory:
```
wget http://files.is.tue.mpg.de/mloper/opendr/osmesa/OSMesa.Linux.x86_64.zip
```
3. create conda environment with python2.7. (opendr only works for python2.x. I use python3.x in the beginning and it failed)
4. install opendr
```
cd opendr && python setup.py install
```

After install, copy the opendr directory to site-packages of your anaconda environment directory (such as: anaconda --> envs --> pythonx.x --> lib --> pythonx.x --> site-packages). Otherwise, you will encounter some errors like:
```
ModuleNotFoundError: No module named 'opendr.contexts.ctx_mesa'
```
Another error may occur:
```
No module names '_constraints'
```
This can be fixed with modifying the line which import _constants.py to absolute path (from opendr.contexts._constants import *) in opendr/contexts/ctx_base.pyx

**Comment by delaprada** [comment]
> I have successfully installed opendr with python2, but not with `pip install opendr`.
> 
> take the following steps:
> 
> 1. git clone opendr repo:
> 
> ```
> git clone https://github.com/mattloper/opendr
> ```
> 
> 2. wget download OSMesa to `opendr/contexts` directory:
> 
> ```
> wget http://files.is.tue.mpg.de/mloper/opendr/osmesa/OSMesa.Linux.x86_64.zip
> ```
> 
> 3. create conda environment with python2.7. (opendr only works for python2.x. I use python3.x in the beginning and it failed)
> 4. install opendr
> 
> ```
> cd opendr && python setup.py install
> ```
> 
> After install, copy the opendr directory to site-packages of your anaconda environment directory (such as: anaconda --> envs --> pythonx.x --> lib --> pythonx.x --> site-packages). Otherwise, you will encounter some errors like:
> 
> ```
> ModuleNotFoundError: No module named 'opendr.contexts.ctx_mesa'
> ```
> 
> Another error may occur:
> 
> ```
> No module names '_constraints'
> ```
> 
> This can be fixed with modifying the line which import _constants.py to absolute path (from opendr.contexts._constants import *) in opendr/contexts/ctx_base.pyx

This is the conda list:

```
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main  
_openmp_mutex             5.1                       1_gnu  
backports-functools-lru-cache 1.6.6                    pypi_0    pypi
ca-certificates           2023.08.22           h06a4308_0  
certifi                   2020.6.20          pyhd3eb1b0_3  
chumpy                    0.70                     pypi_0    pypi
cloudpickle               1.3.0                    pypi_0    pypi
cycler                    0.10.0                   pypi_0    pypi
cython                    3.0.5                    pypi_0    pypi
decorator                 4.4.2                    pypi_0    pypi
kiwisolver                1.1.0                    pypi_0    pypi
libffi                    3.4.4                h6a678d5_0  
libgcc-ng                 11.2.0               h1234567_1  
libgomp                   11.2.0               h1234567_1  
libstdcxx-ng              11.2.0               h1234567_1  
matplotlib                2.2.5                    pypi_0    pypi
ncurses                   6.4                  h6a678d5_0  
networkx                  2.2                      pypi_0    pypi
numpy                     1.16.6                   pypi_0    pypi
opencv-python             4.2.0.32                 pypi_0    pypi
opendr                    0.77                     pypi_0    pypi
pillow                    6.2.2                    pypi_0    pypi
pip                       19.3.1                   py27_0  
pyparsing                 2.4.7                    pypi_0    pypi
python                    2.7.18               h42bf7aa_3  
python-dateutil           2.8.2                    pypi_0    pypi
pytz                      2023.3.post1             pypi_0    pypi
pywavelets                1.0.3                    pypi_0    pypi
readline                  8.2                  h5eee18b_0  
scikit-image              0.14.5                   pypi_0    pypi
scipy                     1.2.3                    pypi_0    pypi
setuptools                44.0.0                   py27_0  
six                       1.16.0                   pypi_0    pypi
sqlite                    3.41.2               h5eee18b_0  
subprocess32              3.5.4                    pypi_0    pypi
tk                        8.6.12               h1ccaba5_0  
transforms3d              0.3.1                    pypi_0    pypi
wheel                     0.37.1             pyhd3eb1b0_0  
zlib                      1.2.13               h5eee18b_0 
```
