### ISSUE TITLE
test_renderer fails

### ISSUE THREAD

**Issue by mshafiei** [mattloper/opendr#26]
Hi,

I try test_renderer and I get the following error,

> test_cam_derivatives (__main__.TestRenderer) ... ERROR
> test_color_derivatives (__main__.TestRenderer) ... ERROR
> test_distortion (__main__.TestRenderer) ... ERROR
> test_lightpos_derivatives (__main__.TestRenderer) ... ERROR
> test_pyramids (__main__.TestRenderer)
> Test that pyramid construction doesn't crash. No quality testing here. ... ERROR
> test_vert_derivatives (__main__.TestRenderer) ... ERROR
> 
> ======================================================================
> ERROR: test_cam_derivatives (__main__.TestRenderer)
> ----------------------------------------------------------------------
> Traceback (most recent call last):
>   File "test_renderer.py", line 213, in test_cam_derivatives
>     r = renderer.r
>   File "/home/mohammad/anaconda2/lib/python2.7/site-packages/chumpy/ch.py", line 594, in r
>     self._call_on_changed()
>   File "/home/mohammad/anaconda2/lib/python2.7/site-packages/chumpy/ch.py", line 589, in _call_on_changed
>     self.on_changed(self._dirty_vars)
>   File "/media/mohammad/D43ADD7F3ADD5ED4/Mohammad/RelightingDynamic/SMPL-dataset/smpl-python/opendr/renderer.py", line 320, in on_changed
>     self.glf = OsContext(w, h, typ=GL_FLOAT)
>   File "contexts/ctx_mesa.pyx", line 62, in contexts.ctx_mesa.OsContextRaw.__init__
>     self.image = np.zeros((h,w,3), dtype=np.float32)
> TypeError: 'float' object cannot be interpreted as an index
> 
> ======================================================================
> ERROR: test_color_derivatives (__main__.TestRenderer)
> ----------------------------------------------------------------------
> Traceback (most recent call last):
>   File "test_renderer.py", line 434, in test_color_derivatives
>     r = renderer.r
>   File "/home/mohammad/anaconda2/lib/python2.7/site-packages/chumpy/ch.py", line 594, in r
>     self._call_on_changed()
>   File "/home/mohammad/anaconda2/lib/python2.7/site-packages/chumpy/ch.py", line 589, in _call_on_changed
>     self.on_changed(self._dirty_vars)
>   File "/media/mohammad/D43ADD7F3ADD5ED4/Mohammad/RelightingDynamic/SMPL-dataset/smpl-python/opendr/renderer.py", line 320, in on_changed
>     self.glf = OsContext(w, h, typ=GL_FLOAT)
>   File "contexts/ctx_mesa.pyx", line 62, in contexts.ctx_mesa.OsContextRaw.__init__
>     self.image = np.zeros((h,w,3), dtype=np.float32)
> TypeError: 'float' object cannot be interpreted as an index
> 
> ======================================================================
> ERROR: test_distortion (__main__.TestRenderer)
> ----------------------------------------------------------------------
> Traceback (most recent call last):
>   File "test_renderer.py", line 125, in test_distortion
>     im_original = renderer.r.copy()
>   File "/home/mohammad/anaconda2/lib/python2.7/site-packages/chumpy/ch.py", line 594, in r
>     self._call_on_changed()
>   File "/home/mohammad/anaconda2/lib/python2.7/site-packages/chumpy/ch.py", line 589, in _call_on_changed
>     self.on_changed(self._dirty_vars)
>   File "/media/mohammad/D43ADD7F3ADD5ED4/Mohammad/RelightingDynamic/SMPL-dataset/smpl-python/opendr/renderer.py", line 470, in on_changed
>     super(TexturedRenderer, self).on_changed(which)
>   File "/media/mohammad/D43ADD7F3ADD5ED4/Mohammad/RelightingDynamic/SMPL-dataset/smpl-python/opendr/renderer.py", line 320, in on_changed
>     self.glf = OsContext(w, h, typ=GL_FLOAT)
>   File "contexts/ctx_mesa.pyx", line 62, in contexts.ctx_mesa.OsContextRaw.__init__
>     self.image = np.zeros((h,w,3), dtype=np.float32)
> TypeError: 'float' object cannot be interpreted as an index
> 
> ======================================================================
> ERROR: test_lightpos_derivatives (__main__.TestRenderer)
> ----------------------------------------------------------------------
> Traceback (most recent call last):
>   File "test_renderer.py", line 364, in test_lightpos_derivatives
>     dr = renderer.dr_wrt(light1_pos).copy()
>   File "/home/mohammad/anaconda2/lib/python2.7/site-packages/chumpy/ch.py", line 732, in dr_wrt
>     self._call_on_changed()
>   File "/home/mohammad/anaconda2/lib/python2.7/site-packages/chumpy/ch.py", line 589, in _call_on_changed
>     self.on_changed(self._dirty_vars)
>   File "/media/mohammad/D43ADD7F3ADD5ED4/Mohammad/RelightingDynamic/SMPL-dataset/smpl-python/opendr/renderer.py", line 320, in on_changed
>     self.glf = OsContext(w, h, typ=GL_FLOAT)
>   File "contexts/ctx_mesa.pyx", line 62, in contexts.ctx_mesa.OsContextRaw.__init__
>     self.image = np.zeros((h,w,3), dtype=np.float32)
> TypeError: 'float' object cannot be interpreted as an index
> 
> ======================================================================
> ERROR: test_pyramids (__main__.TestRenderer)
> Test that pyramid construction doesn't crash. No quality testing here.
> ----------------------------------------------------------------------
> Traceback (most recent call last):
>   File "test_renderer.py", line 93, in test_pyramids
>     rn_pyr = gaussian_pyramid(rn, normalization=None, n_levels=2)
>   File "/media/mohammad/D43ADD7F3ADD5ED4/Mohammad/RelightingDynamic/SMPL-dataset/smpl-python/opendr/filters.py", line 71, in gaussian_pyramid
>     cur_imshape = cur_obj.output_shape
>   File "/media/mohammad/D43ADD7F3ADD5ED4/Mohammad/RelightingDynamic/SMPL-dataset/smpl-python/opendr/filters.py", line 114, in output_shape
>     self._call_on_changed() # trigger changes from im_shape
>   File "/home/mohammad/anaconda2/lib/python2.7/site-packages/chumpy/ch.py", line 589, in _call_on_changed
>     self.on_changed(self._dirty_vars)
>   File "/media/mohammad/D43ADD7F3ADD5ED4/Mohammad/RelightingDynamic/SMPL-dataset/smpl-python/opendr/filters.py", line 102, in on_changed
>     self.transf_mtx, self._output_shape = filter_for_nopadding(sh, self.kernel)
>   File "/media/mohammad/D43ADD7F3ADD5ED4/Mohammad/RelightingDynamic/SMPL-dataset/smpl-python/opendr/filters.py", line 180, in filter_for_nopadding
>     xs = np.tile(np.arange(old_w), (old_h, 1))
>   File "/home/mohammad/anaconda2/lib/python2.7/site-packages/numpy/lib/shape_base.py", line 1157, in tile
>     return c.reshape(shape_out)
> TypeError: 'float' object cannot be interpreted as an index
> 
> ======================================================================
> ERROR: test_vert_derivatives (__main__.TestRenderer)
> ----------------------------------------------------------------------
> Traceback (most recent call last):
>   File "test_renderer.py", line 293, in test_vert_derivatives
>     r = renderer.r
>   File "/home/mohammad/anaconda2/lib/python2.7/site-packages/chumpy/ch.py", line 594, in r
>     self._call_on_changed()
>   File "/home/mohammad/anaconda2/lib/python2.7/site-packages/chumpy/ch.py", line 589, in _call_on_changed
>     self.on_changed(self._dirty_vars)
>   File "/media/mohammad/D43ADD7F3ADD5ED4/Mohammad/RelightingDynamic/SMPL-dataset/smpl-python/opendr/renderer.py", line 320, in on_changed
>     self.glf = OsContext(w, h, typ=GL_FLOAT)
>   File "contexts/ctx_mesa.pyx", line 62, in contexts.ctx_mesa.OsContextRaw.__init__
>     self.image = np.zeros((h,w,3), dtype=np.float32)
> TypeError: 'float' object cannot be interpreted as an index
> 
> ----------------------------------------------------------------------
> Ran 6 tests in 0.779s
> 
> FAILED (errors=6)
> --Return--
> > /media/mohammad/D43ADD7F3ADD5ED4/Mohammad/RelightingDynamic/SMPL-dataset/smpl-python/opendr/test_renderer.py(496)<module>()->None
> -> import pdb; pdb.set_trace()
> (Pdb) q
> Traceback (most recent call last):
>   File "test_renderer.py", line 496, in <module>
>     import pdb; pdb.set_trace()
>   File "/home/mohammad/anaconda2/lib/python2.7/bdb.py", line 53, in trace_dispatch
>     return self.dispatch_return(frame, arg)
>   File "/home/mohammad/anaconda2/lib/python2.7/bdb.py", line 91, in dispatch_return
>     if self.quitting: raise BdbQuit
> bdb.BdbQuit

I am using anaconda python 2.7, ubuntu 18.04 64bit

**Comment by SolmazJaunt** [comment]
Any update on this?
