### ISSUE TITLE
the problem of  "ImportError: No module named ctx_mesa"

### ISSUE THREAD

**Issue by zjw689** [mattloper/opendr#48]
pip install opendr==0.77,  and it is successfully. Then, enter into the environment of python, input the test of demo "import opendr
opendr.demo('spherical_harmonics')".
But the error is as below:
"Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "opendr/__init__.py", line 350, in demo
    exec('global np\n' + demos[which], globals(), locals())
  File "<string>", line 5, in <module>
  File "opendr/renderer.py", line 25, in <module>
    from .contexts.ctx_mesa import OsContext
ImportError: No module named ctx_mesa"

**Comment by zjw689** [comment]
can any dear teacher help me？ The python is  2.7，OS is ubuntu 18.04

**Comment by zjw689** [comment]
@algrs @classner @paulmelnikow @mattloper

**Comment by paulmelnikow** [comment]
Hi, sorry, I can't help with this.

**Comment by classner** [comment]
Hi @zjw689 !

I'm not a maintainer of this package, but if I recall correctly this means that the installation is not complete and lacks the OS specific components for rendering. During installation, I think this method ( https://github.com/mattloper/opendr/blob/master/setup.py#L31 ) should take care of it, so you could check whether this is done successfully. @mattloper could probably provide more details.

**Comment by zjw689** [comment]
> Hi @zjw689 !
> 
> I'm not a maintainer of this package, but if I recall correctly this means that the installation is not complete and lacks the OS specific components for rendering. During installation, I think this method ( https://github.com/mattloper/opendr/blob/master/setup.py#L31 ) should take care of it, so you could check whether this is done successfully. @mattloper could probably provide more details.

Thank you very much. But it dose not work.

**Comment by ljq2020** [comment]
I met the same problem, did you solve it?

**Comment by ljq2020** [comment]
I met the same problem, have you solve it?

**Comment by NguyenTriTrinh** [comment]
I guess `python setup.py build_ext --inplace` may help you.

**Comment by SMY19999** [comment]
I have solved this problem. Please go to this [webpage](https://blog.csdn.net/qq_40520596/article/details/110955392), which in Chinese.
I use Python 2.7 and follow the "二、手动安装" instruction. 
In fact, we need to add step 7 : python setup.py build_ext --inplace
The terminal will print:
`running build_ext
copying build/lib.linux-x86_64-2.7/opendr/contexts/ctx_mesa.so -> ./contexts`
That's all.

**Comment by SMY19999** [comment]
Based on my last reply, 

> ###
> **[xiaoyang-RL9](/xiaoyang-RL9) ** commented [Mar 1, 2023](#issuecomment-1450192418) •

I solve the problem by modifying some code.

As the error said, it is the opendr/contexts/ctx_base.pyx, code : from _constants import *. And the error is no module named _constancts. 

So I check the _constants.py in the same root directory, it just contains some names, just copy them and put them on the top of ctx_base.pyx. And delete from _constants import *. 

After doing such modification, you can install opendr manually following my last reply. Test it by

import opendr

opendr.demo('texture')

You will see an earth.

My venv is python2.7, created by conda.

**Comment by Litt1eMarsun** [comment]
@zjw689 哈咯校友，请问现在你解决了这个问题了吗

**Comment by Litt1eMarsun** [comment]
@zjw689  哈咯校友，请问现在解决了这个问题了吗
